version: "3.9"

services:
  backend:
    build: ./backend
    container_name: planning_backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 1 --threads 4
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /Users/jc/Documents/TigoCrea/dataSource:/data_container
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped

  celery:
    build: ./backend
    container_name: planning_celery
    command: celery -A backend worker -l info --pool=solo
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /Users/jc/Documents/TigoCrea/dataSource:/data_container
    depends_on:
      - backend
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: planning_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  frontend:
      build:
        context: ./front
        args:
          - VITE_API_URL=${VITE_API_URL}
      container_name: planning_frontend
      ports:
        - "3005:80"
      depends_on:
        - backend
      restart: unless-stopped


